---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - net-tools
      - dnsutils
      - wget
      - curl
      - mc
      - rsync
    state: present

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
